### ISSUE TITLE
'/' is not allowed in domains

### ISSUE THREAD

**Issue by alexcrichton** [servo/rust-url#26] opened 2014-09-03 16:59 UTC
For example, this url does not parse:

```
postgres://postgres@%2Fvar%2Frun%2Fpostgresql
```

This is hindering rust-postgres's move to rust-url, and @sfackler points out page 20 of http://tools.ietf.org/html/rfc3986#section-3.2.2 which seems to allow for this.

**Comment by galsondor** [comment] 2015-02-05 00:55
@alexcrichton I think the basic issue here is that the first %2F should not be encoded.  Thus the parser does not know where the path starts and the %2F is taken as part of the host name.  RFC 3986 2.4 says "When a URI is dereferenced, the components ... must be ... separated before the percent-encoded octets ... can be safely decoded,...".  What is the context that created this particular URL?  Do the path components really need to be percent encoded?

**Comment by sfackler** [comment] 2015-02-05 00:59
@galsondor it comes from PostgreSQL's connection strings - see the bottom of section 31.1.1.2 here: http://www.postgresql.org/docs/9.4/static/libpq-connect.html#LIBPQ-CONNSTRING

**Comment by mikedilger** [comment] 2015-02-05 00:59
@galsondor an example URL would be this:  postgresql://postgres@%2Fvar%2Flib%2Fpostgresql/dbname

The %2F encodings are to keep those slashes from having "URL" meaning, and pass them through, as they have "postgres" meaning.

**Comment by galsondor** [comment] 2015-02-05 01:07
@sfackler and @mikedilger, got it; thanks for the references.  RFC 3986 2.4 also says that percent encodings should remain encoded until dereferenced, which in this case is probably the PostgresSQL client's job.  Since the point of rust-url is to parse (presumably in order to deference), perhaps this URL should remain a string until passed to the client.  (Obviously there is a lot I don't know about your application, please forgive me if I am off base here.)

**Comment by mikedilger** [comment] 2015-02-05 01:14
In sfackler's instance (rust-postgres) he is parsing it to determine how to setup the connection to the PostgreSQL server.  I should hope a URL library could help him out, as the rest of the URL is formed very much like any other URL.

It comes down to the WhatWG's definition of a URL and in particular the heirarchy they choose for seeing a URL as.  That hierarchy is, IMHO, not quite right, and this is a very good example of why.

**Comment by SimonSapin** [comment] 2015-02-05 01:16
@mikedilger what do you mean by hierarchy? The problem here is that, per spec, percent-encoding does not apply to host names.

**Comment by galsondor** [comment] 2015-02-05 01:25
@SimonSapin Percent encoding can be used in host names. Per RFC 3986: "host = IP-literal / IPv4address / reg-name" and "reg-name = *( unreserved / pct-encoded / sub-delims )".  I think the issue is that "%2F..." a host name an the traditional, DNS sense.  Postgres "netlocs" can be a path to a configuration directory on the local host. Thus, Postgres URLs can have two paths: the "netloc", which is in the host, and the "dbname", which is in the path.

**Comment by mikedilger** [comment] 2015-02-05 01:27
@SimonSapin 

The issue of parsing percent encoding in a relative scheme is, yes, an interesting issue but I think it's moot because postgres is not a relative scheme (according to how that is aparently defined).

I'm referring to the hierarchy of the url components, what boundaries do you break down first, and then which of those breaks down further.   Under WhatWG and this library (vs. the old rust url library) the notion of a "Relative Scheme" arises and includes (username,password,host,port,default_port,path), and as postgresql is not listed as a relative scheme (as that is how relative scheme seems to be defined), it is therefore a non-relative scheme, and therefore there is no parsing assistance available for any of those 6 components, you just get NonRelative(String) and are on your own.

**Comment by mikedilger** [comment] 2015-02-05 02:10
Sorry, I've taken this off topic (although there is overlap).  I may be confusing issues somewhat with #2.

**Comment by nox** [comment] 2016-03-24 15:57
I found something that avoids the problem altogether: PostgreSQL also allows components through query parameters:

```
postgres:///<db name>?host=/tmp
```

This doesn't immediately help because this is still a invalid URL (note the empty host in `///`), but I just checked that the parameter takes precedence over the real host of the connection URL. For example, this will connect to the socket in `/tmp`:

```
postgres://dummy/<db name>?host=/tmp
```

With this, I think this is not a problem anymore!

**Comment by SimonSapin** [comment] 2016-04-04 15:33
@sfackler, is @nox’s suggestion acceptable? If not we can add a opt-in flag to change the parsing behavior, though I’d rather do it after #176 lands to avoid yet another rebase.

**Comment by nox** [comment] 2017-03-04 11:32
I am closing this.

**Closed by nox** 2017-03-04 11:32 UTC
