### ISSUE TITLE
to_file_path() on localhost returns Path::new("/")

### ISSUE THREAD

**Issue by alexcrichton** [servo/rust-url#24] opened 2014-09-03 16:09 UTC
For example, this program will print `/`

``` rust
extern crate url;                                                 

use url::Url;                                                     

fn main() {                                                       
    let url = Url::parse("http://postgres@localhost/").unwrap();  
    println!("{}", url.to_file_path::<Path>().unwrap().display());
}                                                                 
```

Is this expected? If so, is there a way to differentiate paths with hosts from those with paths? It also looks like [this may be relevant](https://github.com/servo/rust-url/blob/d894135cac4e0085f41ba3a816240b792f9e6154/src/lib.rs#L823)

**Comment by SimonSapin** [comment] 2016-04-21 07:23
`to_file_path` doesn’t have a type parameter anymore, but other than that this behavior hasn’t changed. Still, it matches the doc-comment. What outcome would you rather have?

> Assuming the URL is in the `file` scheme or similar, convert its path to an absolute `std::path::Path`.
>
> **Note:** This does not actually check the URL’s `scheme`, and may give nonsensical results for other schemes. It is the user’s responsibility to check the URL’s scheme before calling this.
>
> ```
> # use url::Url;
> # let url = Url::parse("file:///etc/passwd").unwrap();
> let path = url.to_file_path();
> ```
>
> Returns `Err` if the host is neither empty nor `"localhost"`, or if `Path::new_opt()` returns `None`. (That is, if the percent-decoded path contains a NUL byte or, for a Windows path, is not UTF-8.)

**Comment by dtolnay** [comment] 2017-05-12 05:46
Based on the function's documentation, it seems like this is behaving correctly. What action is this issue tracking?

**Comment by SimonSapin** [comment] 2018-10-17 11:42
Closing as working as intended / document. Feel free to reopen or comment.

**Closed by SimonSapin** 2018-10-17 11:42 UTC
