### ISSUE TITLE
Surprising behaviour for non-standard file-like special schemes

### ISSUE THREAD

**Issue by okey** [servo/rust-url#464] opened 2018-10-26 19:58 UTC
`host()` returns the empty string rather than `None` for urls with file-like special schemes.

For example, parsing `"file:///tmp/foo.quux"` will have `None` as the host while `"unix:///tmp/bar.sock"` will have the empty string.

I initially found this behaviour surprising. Is it intentional?

Code:
```Rust
extern crate url;
use url::Url;

fn main() {
    let file = Url::parse("file:///tmp/foo.quux").unwrap();
    let fhs = file.host().map_or("None".to_string(), |h| h.to_string());
    println!("url:{}, has_host={}, host='{}'", file, file.has_host(), fhs);

    let sckt = Url::parse("unix:///tmp/bar.sock").unwrap();
    let shs = sckt.host().map_or("None".to_string(), |h| h.to_string());
    println!("url:{}, has_host={}, host='{}'", sckt, sckt.has_host(), shs);
}
```
Output:

```
url:file:///tmp/foo.quux, has_host=false, host='None'
url:unix:///tmp/bar.sock, has_host=true, host=''
```

**Comment by nox** [comment] 2019-07-18 11:08
That's a duplicate of #465.

**Closed by nox** 2019-07-18 11:08 UTC

**Comment by okey** [comment] 2019-07-18 21:07
@nox Is this really the same as #465?

#465 is basically asking why `to_file_path()` fails on schemes other than `file://`.

Here I'm asking why the host for a `file://` is parsed to `None` but the host for an arbitrary non-special scheme, in this case `unix://`, is parsed to the empty string.

P.S. According to [whatwg](https://url.spec.whatwg.org/#url-representation) both the file scheme and non-special schemes may have null or empty hosts, unlike other special schemes, so this is at worst a slight inconsistency.
