### ISSUE TITLE
Compile-time url parsing 'url!' macro

### ISSUE THREAD

**Issue by frewsxcv** [servo/rust-url#136] opened 2015-11-18 23:31 UTC
Inspired by [sfackler/rust-postgres-macros](https://github.com/sfackler/rust-postgres-macros) which is a compile time SQL parser

There are ton of instances in servo, where we do something like `Url::parse("http://mozilla.com").unwrap()`. It'd be great if we could do that validation at compile time with a macro (e.g. `url!("http://mozilla.com")`).

I have no idea how feasible this is, just throwing around the idea.

**Comment by SimonSapin** [comment] 2015-11-18 23:40
Sounds feasible with a plugin, maybe not specific to URLs. Anything that implements `FromStr`?

**Comment by KiChjang** [comment] 2015-11-18 23:41
I wonder whether regex would be enough to parse URLs? The language of URLs seem regular enough to me (I may be wrong though).

**Comment by SimonSapin** [comment] 2015-11-18 23:52
@KiChjang A regex may(?) be able to separate the components of an URL, but the parser as specified in https://url.spec.whatwg.org/#url-parsing does more stuff along the way such as percent-decoding, IDNA, resolving relative URLs, normalizing (anti)slashes, collapsing `.` and `..` path components, etc. Anyway, this is unrelated to this issue.

Making a plugin generic over `T: FromStr` wouldn’t work, the plugin needs to know at its own compile-time which crates it should depend on.

Another approach might be to skip string parsing entirely. All fields of `Url` are public, so it can be constructed directly as a struct literal.

**Comment by SimonSapin** [comment] 2015-11-19 00:12
Larger explanation of the above, copied from IRC:

* SimonSapin: You can make a compiler plugin (syntax extension) so that url!("http://example") runs `Url::parse()` at compile time and expands the result to a struct literal. Then I was thinking, why not generalize this to anything that implements FromStr?
* SimonSapin: like `from_str!(::url::Url, "http://example")`
* SimonSapin: the problem is that by the time such a plugin would see the ::url::Url path, it’s already compiled and can not add to itself a new dependency to the url crate

**Comment by frewsxcv** [comment] 2015-11-19 00:27
@SimonSapin @KiChjang just to prevent duplicate efforts, are either of you working on this currently?

**Comment by KiChjang** [comment] 2015-11-19 00:29
No I'm not working on it at all. You can assign the issue to yourself.

**Comment by frewsxcv** [comment] 2015-11-20 04:31
Opened a PR #137

**Comment by nox** [comment] 2015-11-21 09:30
#137

**Closed by nox** 2015-11-21 09:30 UTC

**Comment by DenisGorbachev** [comment] 2024-07-19 22:28
You can use the [`url-macro`](https://crates.io/crates/url-macro) crate that provides `url!` macro for compile-time validation
