### ISSUE TITLE
Missing "/" in path when url contains a scheme other than "https"

### ISSUE THREAD

**Issue by slondr** [servo/rust-url#773] opened 2022-06-09 00:52 UTC
Hi, I've been chasing down a bug in my application to this behavior which seems inconsistent with the docs. For example

```rust
    #[test]
    fn url_parsing_library_is_sane() {
	let url = url::Url::parse("https://example.com").unwrap();
	assert_eq!(url.path(), "/"); // passes
    }

    #[test]
    fn url_parsing_library_is_sane_2() {
	let url = url::Url::parse("spartan://example.com").unwrap();
	assert_eq!(url.path(), "/") // fails
    }

    #[test]
    fn url_parsing_library_is_sane_3() {
	let url = url::Url::parse("spartan://example.com").unwrap();
	assert!(!url.cannot_be_a_base()); // passes
    }

    #[test]
    fn url_parsing_library_is_sane_4() {
	let url = url::Url::parse("asdfuiop://example.com").unwrap();
	assert_eq!(url.path(), "/") // fails
    }

```

The docs for `path` mention:
> For cannot-be-a-base URLs, this is an arbitrary string that doesn’t start with ‘/’. For other URLs, this starts with a ‘/’ slash and continues with slash-separated path segments.

It seems like URLs with a scheme other than HTTPS are correctly identified as can be a base, but the path does not start with / anyway. If I'm reading the docs correctly, all four of these tests should pass.

**Comment by erickt** [comment] 2022-11-18 19:18
I bisected this change down to being introduced in #537 and released in v2.1.1, specifically the commit https://github.com/servo/rust-url/commit/9cd646.

@o0Ignition0o and @nox - is this expected behavior, or is this a bug?

**Comment by o0Ignition0o** [comment] 2022-12-30 13:41
Hey, sorry for the late reply. Good question, I m gonna check

**Comment by o0Ignition0o** [comment] 2022-12-30 13:47
It looks like a but to me: 

Section 8 of [scheme state](https://url.spec.whatwg.org/#ref-for-scheme-state) mentions:

```
Otherwise, if [remaining](https://url.spec.whatwg.org/#remaining) starts with an U+002F (/), set state to [path or authority state](https://url.spec.whatwg.org/#path-or-authority-state) and increase pointer by 1.
```

Let's see if I can write a test case.

**Comment by o0Ignition0o** [comment] 2022-12-30 13:55
I understand [this sentence](https://url.spec.whatwg.org/#concept-url-path):

A [special](https://url.spec.whatwg.org/#is-special) [URL](https://url.spec.whatwg.org/#concept-url)’s [path](https://url.spec.whatwg.org/#concept-url-path) is always a [list](https://infra.spec.whatwg.org/#list), i.e., it is never [opaque](https://url.spec.whatwg.org/#url-opaque-path).

As "Special schemes always have at least an emty list as path", but I don't see it apply to non special schemes. I'm going to browse a bit more

**Comment by o0Ignition0o** [comment] 2022-12-30 14:01
The [Path getter documentation](https://github.com/servo/rust-url/blob/1c1e406874b3d2aa6f36c5d2f3a5c2ea74af9efb/url/src/lib.rs#L1215) claims otherwise though.

**Comment by o0Ignition0o** [comment] 2022-12-30 14:05
This seems to be aligned with the comment @SimonSapin wrote in [the path() getter](https://github.com/servo/rust-url/blob/1c1e406874b3d2aa6f36c5d2f3a5c2ea74af9efb/url/src/lib.rs#L1215):

```
    /// Return the path for this URL, as a percent-encoded ASCII string.
    /// For cannot-be-a-base URLs, this is an arbitrary string that doesn’t start with '/'.
    /// For other URLs, this starts with a '/' slash
    /// and continues with slash-separated path segments.
```

Cannot be a base URLs only happen to special URLs.

**Comment by annevk** [comment] 2023-02-06 10:21
Right, this is by design. I recommend closing this bug and perhaps adding documentation that if you want your custom scheme to have similar processing to a special scheme you need to implement that on top in a processor of sorts.

**Comment by riccardodivirgilio** [comment] 2023-02-24 15:00
Hi I have been investigating a similar inconsistency as well, so I'm reporting my findings here, instead I'm reporting my findings here:

```rust

use url::{Host, Url};

fn url_parse(s: String) {

    let result = Url::parse(&s);


    println!("parsing: {}", s);

    match result {
        Ok(parsed) => {
            println!("scheme: {}", parsed.scheme());

            match parsed.host() {
                Some(Host::Domain(s)) => println!("host: {}", s),
                Some(Host::Ipv4(s)) => println!("host: {}", &s.to_string()),
                Some(Host::Ipv6(s)) => println!("host: {}", &s.to_string()),
                _  => println!("host: -"),
            }

            println!("path: {}", parsed.path());

        }
        Err(error) => {

            println!("error: {}", error);
        },
    }

    println!("");

}

fn main() {
    // Statements here are executed when the compiled binary is called

    url_parse("file://ciao//bye".to_string());
    url_parse("http://ciao//bye".to_string());

    // Print text to the console
    url_parse("file:///ciao//bye".to_string());
    url_parse("http:///ciao//bye".to_string());
}
```

The output of this program is:

```
parsing: file://ciao//bye
scheme: file
host: ciao
path: /bye

parsing: http://ciao//bye
scheme: http
host: ciao
path: //bye

parsing: file:///ciao//bye
scheme: file
host: -
path: /ciao//bye

parsing: http:///ciao//bye
scheme: http
host: ciao
path: //bye
```

an identical program written in python is this one:

```python

from urllib.parse import urlparse

def url_parse(url):
    parsed = urlparse(url)
    print('parsing: ', url)
    print('scheme: ', parsed.scheme)
    print('host: ', parsed.netloc)
    print('path: ', parsed.path)
    print('')


url_parse("file://ciao//bye")
url_parse("http://ciao//bye")

url_parse("file:///ciao//bye")
url_parse("http:///ciao//bye")
```

and it would output the following:

```
parsing:  file://ciao//bye
scheme:  file
host:  ciao
path:  //bye

parsing:  http://ciao//bye
scheme:  http
host:  ciao
path:  //bye

parsing:  file:///ciao//bye
scheme:  file
host:  
path:  /ciao//bye

parsing:  http:///ciao//bye
scheme:  http
host:  
path:  /ciao//bye
```

in particular python behaviour seems to be doing a better job in keeping trailing slashes in path, that in rust are silently dropped in some specific circumstances (file scheme vs http), and it has a more coherent behaviour regardless of the scheme. also the parsed outcome of "http:///ciao//bye" seems to be completely wrong in rust...

**Comment by valenting** [comment] 2023-02-27 10:39
> also the parsed outcome of "http:///ciao//bye" seems to be completely wrong in rust...

It parses correctly [as far as I can see](https://jsdom.github.io/whatwg-url/#url=aHR0cDovLy9jaWFvLy9ieWU=&base=YWJvdXQ6Ymxhbms=)

**Closed by valenting** 2023-02-27 10:39 UTC
