### ISSUE TITLE
Url::to_file_path fails for any non "file:"-scheme

### ISSUE THREAD

**Issue by faulesocke** [servo/rust-url#493] opened 2019-04-17 06:50 UTC
The `Url::to_file_path` method fails when the scheme was not `file:` but for example `unix:`.

Small test code to reproduce the error:
```rust
fn main() {
    use url::Url;
    let url = "unix:///tmp/test.sock";
    //let url = "file:///tmp/test.sock";
    let url = Url::parse(url).unwrap();
    println!("{:#?}", url);

    println!("file_path {:#?}", url.to_file_path());
    println!("path_segments {:#?}", url.path_segments());
    println!("host {:#?}", url.host());
    println!("schema {:#?}", url.scheme());
}
```

The output is:
```
"unix:///tmp/test.sock"
file_path Err(
    (),
)
path_segments Some(
    Split(
        SplitInternal {
            start: 0,
            end: 13,
            matcher: CharSearcher {
                haystack: "tmp/test.sock",
                finger: 0,
                finger_back: 13,
                needle: '/',
                utf8_size: 1,
                utf8_encoded: [
                    47,
                    0,
                    0,
                    0,
                ],
            },
            allow_trailing_empty: true,
            finished: false,
        },
    ),
)
host Some(
    Domain(
        "",
    ),
)
schema "unix"
```

Observe that `host` is not `None` but some empty string, therefore the check in https://github.com/servo/rust-url/blob/master/src/lib.rs#L2350 fails.

When you change the scheme to `file:` the output becomes:
```
"file:///tmp/test.sock"
file_path Ok(
    "/tmp/test.sock",
)
path_segments Some(
    Split(
        SplitInternal {
            start: 0,
            end: 13,
            matcher: CharSearcher {
                haystack: "tmp/test.sock",
                finger: 0,
                finger_back: 13,
                needle: '/',
                utf8_size: 1,
                utf8_encoded: [
                    47,
                    0,
                    0,
                    0,
                ],
            },
            allow_trailing_empty: true,
            finished: false,
        },
    ),
)
host None
schema "file"
```

And `host` becomes `None`.

I'm on Linux, but this is probably related to #465

**Comment by nox** [comment] 2019-07-18 11:13
Where is this `unix` scheme coming from, on Linux?

**Comment by faulesocke** [comment] 2019-07-22 17:55
Phew, long time ago... I believe I stumbled upon this issue when I was working with influxdb or redis or something.

**Comment by lucacasonato** [comment] 2022-01-28 18:36
This is intentional behaviour. The `file://` protocol has a somewhat special status in the URL spec: 

![image](https://user-images.githubusercontent.com/7829205/151602683-2d04574b-ce9a-4072-8595-6ba1fac29058.png)

File URLs are namely parsed without hostnames, while "other" protocols like "unix" are not. Also see https://url.spec.whatwg.org/

**Comment by lucacasonato** [comment] 2022-01-28 18:38
Actually likely a duplicate of #465

**Closed** 2022-01-31 09:34 UTC
