### ISSUE TITLE
idna 1.0 results in a dependency explosion when being compared to 0.5

### ISSUE THREAD

**Issue by kanpov** [servo/rust-url#1008] opened 2024-12-12 17:15 UTC
- [x] Note that this crate implements the [URL Standard](https://url.spec.whatwg.org/) not RFC 1738 or RFC 3986

**Describe the bug**
`idna 0.5` dependency graph on an empty `mini-sandbox` bin-crate with only `idna` as a dependency:

```
mini-sandbox v0.1.0 (/home/kanpov/Projects/mini-sandbox)
└── idna v0.5.0
    ├── unicode-bidi v0.3.17
    └── unicode-normalization v0.1.24
        └── tinyvec v1.8.0
            └── tinyvec_macros v0.1.1
```

`idna 1` dependency graph in the same conditions:

```
mini-sandbox v0.1.0 (/home/kanpov/Projects/mini-sandbox)
└── idna v1.0.3
    ├── idna_adapter v1.2.0
    │   ├── icu_normalizer v1.5.0
    │   │   ├── displaydoc v0.2.5 (proc-macro)
    │   │   │   ├── proc-macro2 v1.0.92
    │   │   │   │   └── unicode-ident v1.0.14
    │   │   │   ├── quote v1.0.37
    │   │   │   │   └── proc-macro2 v1.0.92 (*)
    │   │   │   └── syn v2.0.90
    │   │   │       ├── proc-macro2 v1.0.92 (*)
    │   │   │       ├── quote v1.0.37 (*)
    │   │   │       └── unicode-ident v1.0.14
    │   │   ├── icu_collections v1.5.0
    │   │   │   ├── displaydoc v0.2.5 (proc-macro) (*)
    │   │   │   ├── yoke v0.7.5
    │   │   │   │   ├── stable_deref_trait v1.2.0
    │   │   │   │   ├── yoke-derive v0.7.5 (proc-macro)
    │   │   │   │   │   ├── proc-macro2 v1.0.92 (*)
    │   │   │   │   │   ├── quote v1.0.37 (*)
    │   │   │   │   │   ├── syn v2.0.90 (*)
    │   │   │   │   │   └── synstructure v0.13.1
    │   │   │   │   │       ├── proc-macro2 v1.0.92 (*)
    │   │   │   │   │       ├── quote v1.0.37 (*)
    │   │   │   │   │       └── syn v2.0.90 (*)
    │   │   │   │   └── zerofrom v0.1.5
    │   │   │   │       └── zerofrom-derive v0.1.5 (proc-macro)
    │   │   │   │           ├── proc-macro2 v1.0.92 (*)
    │   │   │   │           ├── quote v1.0.37 (*)
    │   │   │   │           ├── syn v2.0.90 (*)
    │   │   │   │           └── synstructure v0.13.1 (*)
    │   │   │   ├── zerofrom v0.1.5 (*)
    │   │   │   └── zerovec v0.10.4
    │   │   │       ├── yoke v0.7.5 (*)
    │   │   │       ├── zerofrom v0.1.5 (*)
    │   │   │       └── zerovec-derive v0.10.3 (proc-macro)
    │   │   │           ├── proc-macro2 v1.0.92 (*)
    │   │   │           ├── quote v1.0.37 (*)
    │   │   │           └── syn v2.0.90 (*)
    │   │   ├── icu_normalizer_data v1.5.0
    │   │   ├── icu_properties v1.5.1
    │   │   │   ├── displaydoc v0.2.5 (proc-macro) (*)
    │   │   │   ├── icu_collections v1.5.0 (*)
    │   │   │   ├── icu_locid_transform v1.5.0
    │   │   │   │   ├── displaydoc v0.2.5 (proc-macro) (*)
    │   │   │   │   ├── icu_locid v1.5.0
    │   │   │   │   │   ├── displaydoc v0.2.5 (proc-macro) (*)
    │   │   │   │   │   ├── litemap v0.7.4
    │   │   │   │   │   ├── tinystr v0.7.6
    │   │   │   │   │   │   ├── displaydoc v0.2.5 (proc-macro) (*)
    │   │   │   │   │   │   └── zerovec v0.10.4 (*)
    │   │   │   │   │   ├── writeable v0.5.5
    │   │   │   │   │   └── zerovec v0.10.4 (*)
    │   │   │   │   ├── icu_locid_transform_data v1.5.0
    │   │   │   │   ├── icu_provider v1.5.0
    │   │   │   │   │   ├── displaydoc v0.2.5 (proc-macro) (*)
    │   │   │   │   │   ├── icu_locid v1.5.0 (*)
    │   │   │   │   │   ├── icu_provider_macros v1.5.0 (proc-macro)
    │   │   │   │   │   │   ├── proc-macro2 v1.0.92 (*)
    │   │   │   │   │   │   ├── quote v1.0.37 (*)
    │   │   │   │   │   │   └── syn v2.0.90 (*)
    │   │   │   │   │   ├── stable_deref_trait v1.2.0
    │   │   │   │   │   ├── tinystr v0.7.6 (*)
    │   │   │   │   │   ├── writeable v0.5.5
    │   │   │   │   │   ├── yoke v0.7.5 (*)
    │   │   │   │   │   ├── zerofrom v0.1.5 (*)
    │   │   │   │   │   └── zerovec v0.10.4 (*)
    │   │   │   │   ├── tinystr v0.7.6 (*)
    │   │   │   │   └── zerovec v0.10.4 (*)
    │   │   │   ├── icu_properties_data v1.5.0
    │   │   │   ├── icu_provider v1.5.0 (*)
    │   │   │   ├── tinystr v0.7.6 (*)
    │   │   │   └── zerovec v0.10.4 (*)
    │   │   ├── icu_provider v1.5.0 (*)
    │   │   ├── smallvec v1.13.2
    │   │   ├── utf16_iter v1.0.5
    │   │   ├── utf8_iter v1.0.4
    │   │   ├── write16 v1.0.0
    │   │   └── zerovec v0.10.4 (*)
    │   └── icu_properties v1.5.1 (*)
    ├── smallvec v1.13.2
    └── utf8_iter v1.0.4
```

To put it lightly, this is quite strange for a small utility-crate like this in an update. To put it not so lightly, this is an absurd increase in transitive dependencies for (from a subjective point of view) not really measurable benefit.

How I encountered this issue was running `cargo update` in a project that uses the common `tokio` + `axum` + `tracing-subscriber` + `sqlx` stack that resulted in an increase from 318 dependencies to 358, of which, as can be seen above, a major part is played by `idna`.

Any feedback on this?

**Comment by Manishearth** [comment] 2024-12-12 17:39
Duplicate of https://github.com/servo/rust-url/issues/993. The crate switched to `icu_normalizer` for normalization, which is more maintained.

You can switch `idna_adapter` to a different version to pull in the older backend.

**Closed by Manishearth** 2024-12-12 17:39 UTC
